[package]
name = "m3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy = { path = "../vendor/bevy" }
bevy = "0.5"
#egui = { path = "../vendor/egui/egui" }
egui = "0.13"
bevy_egui = "0.6.2"
